# Generated by Django 4.2.16 on 2024-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0004_dealer_car_alter_carmodel_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(null=True, upload_to="brands/")),
            ],
        ),
    ]
