# Generated by Django 4.2.16 on 2024-09-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0006_alter_carmodel_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
