# Generated by Django 4.2.16 on 2024-09-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0007_alter_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profiles/default.jpg",
                null=True,
                upload_to="profiles/",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
