# Generated by Django 4.2.16 on 2024-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0008_userprofile_image_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profiles/default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
