# Generated by Django 4.2.16 on 2024-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0009_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel", name="price", field=models.CharField(max_length=255),
        ),
    ]
