# Generated by Django 4.2.16 on 2024-09-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0010_alter_carmodel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="car.brand"
            ),
        ),
    ]
